### ISSUE TITLE
Installation on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by muyiwao221** [vdudouyt/mhddfs-nosegfault#1]
When running fakeroot dpkg-buildpackage - I run into this error, and mhddfs-nosegfault is not installed. Not quite sure what to do next. Please help.

dpkg-buildpackage: source package mhddfs
dpkg-buildpackage: source version 0.1.39+nosegfault2
dpkg-buildpackage: source distribution saucy
dpkg-buildpackage: source changed by Valentin Dudouyt valentin.dudouyt@gmail.com
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build mhddfs-nosegfault
 debian/rules clean
dh_testdir
dh_testroot
make clean
make[1]: Entering directory `/root/mhddfs-nosegfault'
rm -fr obj mhddfs pwrite_test statvfs rename
fusermount -u rename-test || true
fusermount: failed to unmount /root/mhddfs-nosegfault/rename-test: No such file or directory
rm -fr rename-test/mnt
make[1]: Leaving directory`/root/mhddfs-nosegfault'
rm -f build-stamp
dh_clean
 dpkg-source -b mhddfs-nosegfault
dpkg-source: info: using source format `3.0 (native)'
dpkg-source: info: building mhddfs in mhddfs_0.1.39+nosegfault2.tar.gz
dpkg-source: info: building mhddfs in mhddfs_0.1.39+nosegfault2.dsc
 debian/rules build
dh_testdir
make
make[1]: Entering directory`/root/mhddfs-nosegfault'
mkdir -p obj
touch obj/obj-stamp
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/debug.c -o obj/debug.o
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/flist.c -o obj/flist.o
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/main.c -o obj/main.o
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/parse_options.c -o obj/parse_options.o
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/tools.c -o obj/tools.o
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 -c src/usage.c -o obj/usage.o
src/usage.c: In function ‘usage’:
src/usage.c:46:2: warning: format not a string literal and no format arguments [-Wformat-security]
  fprintf(to, usage);
  ^
gcc -Wall -D_FILE_OFFSET_BITS=64 -I/usr/local/include/fuse -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2
.0/include   -DFUSE_USE_VERSION=26 -MMD -g -rdynamic -O0 obj/debug.o obj/flist.o obj/main.o obj/parse_options.o obj/t
ools.o obj/usage.o -o mhddfs -pthread -L/usr/local/lib -lfuse -lglib-2.0
make[1]: Leaving directory `/root/mhddfs-nosegfault'
touch build-stamp
 debian/rules binary
dh_testdir
dh_testroot
dh_installchangelogs ChangeLog
dh_installdocs
dh_install
dh_installman
dh_strip
dh_compress
dh_fixperms
dh_installdeb
dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libfuse.so.2 (used by debian/mhddfs/usr/bin
/mhddfs)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/mhddfs.substvars debian/mhddfs/usr/bin/mhddfs returned exit code 2
make: **\* [binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

**Comment by vdudouyt** [comment]
Hi,

Please take a look in 'releases' - I already prepared the backports of 2.9.4.

Best Regards,

Valentin

**Comment by jmelton98** [comment]
> Please take a look in 'releases' - I already prepared the backports of 2.9.4.

Hi, can you help direct me to where I can find the 2.9.4 fuse backport? Is this the best way to update fuse on Debian 7?

Thanks

**Comment by vdudouyt** [comment]
> Hi, can you help direct me to where I can find the 2.9.4 fuse backport? 

Please find it here: https://github.com/vdudouyt/mhddfs-nosegfault/releases/download/0.1.39-3/debian_x64.tar.gz
