### ISSUE TITLE
0.1.39-4 Debian binary?

### ISSUE THREAD

**Issue by Porco-Rosso** [vdudouyt/mhddfs-nosegfault#4]
Is 0.1.39-4 the same as 0.1.39-3, but had to be re-released to comply with GPL?

**Comment by vdudouyt** [comment]
Hi,

No, it was re-released because I have mentioned that the integration with /etc/fstab is not working on CentOS. As for Debian - it was not affected, please consider to use 0.1.39-3.

Best Regards,

Valentin
