### ISSUE TITLE
Easiest way to update Fuse on Debian?

### ISSUE THREAD

**Issue by jmelton98** [vdudouyt/mhddfs-nosegfault#6]
Getting the Fuse dependency error. What's the easiest way to update Fuse? Found .deb file here, is this safe to use?

http://debian.mirror.constant.com/pool/main/f/fuse/

Thanks

**Comment by vdudouyt** [comment]
Hi,

Yes, fuse 2.9.6 should be ok.

**Comment by peterhorsley** [comment]
I'm running Linux Mint (3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:28 UTC 2015 i686 athlon i686 GNU/Linux) so I tried to install the i386 .deb file for libfuse-dev_2.9.7-1_i386.deb, but that needed libfuse2_2.9.7-1_i386.deb, and when i try to install that i get "Error: Conflicts with the installed package 'fuse'.  Any tips on how to update fuse so I can build this?

**Comment by vdudouyt** [comment]
Hi,

You're getting that because version of package named 'fuse' is depending on exact version of 'libfuse2' which is not equal to the one that you're attempting to install. The solution is to download an appropriate version of 'fuse' and install them both with necessarily one dpkg -i call.
